#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo " "
echo "----------------------- Testing --------------------------"
yarn test
echo "=========================================================="
echo " "
echo "--------------- Run Prettier and ESLint ------------------"
# yarn pretty-quick --staged && yarn lint-staged
echo "=========================================================="
echo " "
